- name: Startpage
  width: wide
  hide-desktop-navigation: false
  center-vertically: true

  #searchbar
  head-widgets:
    - type: search
      engine: duckduckgo
      newtab: true
      autofocus: true

  columns:

    - size: small
      widgets:
        - type: to-do
        - type: weather
          units: metric
          location: Eindhoven
          api-key: ${OPENWEATHERMAP_API_KEY}

      # middle column
    - size: full
      widgets:
          # services monitor
        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: PiHole
              url: https://pihole.YOUR_DOMAIN_NAME/admin/
              icon: si:pihole
            - title: Code Server
              url: https://code.YOUR_DOMAIN_NAME
              icon: si:visualstudiocode
            - title: Home Assistant
              url: https://ha.YOUR_DOMAIN_NAME
              icon: si:homeassistant
            - title: Grafana
              url: https://monitor.YOUR_DOMAIN_NAME
              icon: si:grafana

      # right column
    - size: small
      widgets:
          # bookmarks
        - type: bookmarks
          groups:
            - title: Links
              links:
                - title: GitHub
                  url: https://github.com/
                - title: YouTube
                  url: https://www.youtube.com/
                - title: Gmail
                  url: https://mail.google.com/
          # dns stats
        - type: dns-stats
          service: pihole-v6
          url: https://pihole.YOUR_DOMAIN_NAME
          password: ${PIHOLE_PASSWORD}